name: development CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  dev-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Change this if using a different version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest
    - name: Run Biome
      run: biome ci .

    # - name: Install dependencies
    #   run: npm ci

    # - name: Run linter (optional)
    #   run: npm run lint
    #   continue-on-error: true  # Lint failure won't stop the pipeline

    - name: Run tests
      run: npm run test

    - name: Build project (optional)
      run: npm run build
      if: success()
